//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи
    {
        public int ID_продажи { get; set; }
        public Nullable<int> ID_заказа { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    
        public virtual Заказы Заказы { get; set; }
    }
}
