//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Статус_заказа
    {
        public int ID_Статус_заказа { get; set; }
        public Nullable<int> ID_заказа { get; set; }
        public string Статус_заказа1 { get; set; }
        public string Доставщик_заказа { get; set; }
        public string Город_отправления_заказа { get; set; }
        public string Дата_получения { get; set; }
        public string Название { get; set; }
    
        public virtual Заказы Заказы { get; set; }
    }
}
